// contains complex modules and css extensions.
// use with care.

// any element is available in two variants: NO_CSS and normal. NO_CSS does not contain css needed to drive the module.
// Use this together with the module-specific CSS macro to only include the css once, not per element.

#pragma once

#include "microrender.h"

#define MCR_FIXED_HEADERBAR_CSS header,nav{text-align:center;width:100%}*,nav ul{padding:0}*{margin:0}header{z-index:999;padding:.4rem;position:fixed;background:#f4f5f6;border-bottom:.1rem solid #d1d1d1}header input.menu-toggle{display:none}nav{position:absolute;top:100%;left:0;background-color:#f4f5f6;-webkit-transform:scale(1,0);transform:scale(1,0);-webkit-transition:-webkit-transform .4s ease-in-out;transition:transform .4s ease-in-out;transition:transform .4s ease-in-out,-webkit-transform .4s ease-in-out;-webkit-transform-origin:top;transform-origin:top}nav ul{margin:14% 0 0;height:90vh}nav li{margin-left:1rem;height:10%;list-style:none}nav a{text-transform:uppercase;opacity:0}.nav-heading{font-size:3rem}.menu-toggle:checked~nav{-webkit-transform:scale(1,1);transform:scale(1,1)}.menu-toggle:checked~nav a{opacity:1;-webkit-transition:opacity .2s ease-in .1s;transition:opacity .2s ease-in .1s}.menu-nav-toggle{position:absolute;top:0;right:0;height:100%;display:-webkit-box;display:-ms-flexbox;display:flex;-webkit-box-align:center;-ms-flex-align:center;align-items:center;margin-right:2rem}.menu-nav-toggle:focus,.menu-nav-toggle:hover{cursor:pointer}.menu-nav-toggle span,.menu-nav-toggle span:after,.menu-nav-toggle span:before{display:block;background:#333;width:2rem;border-radius:.125rem;position:relative;height:.25rem}.menu-nav-toggle span:after,.menu-nav-toggle span:before{content:'';position:absolute}.menu-nav-toggle span:before{top:.8rem}.menu-nav-toggle span:after{bottom:.8rem}@media screen and (min-width:50rem){.nav-brand,nav{-ms-grid-column-span:1}nav,nav ul{display:-webkit-box;display:-ms-flexbox}.menu-nav-toggle{display:none}header{display:-ms-grid;display:grid;-ms-grid-columns:1fr auto minmax(37.5rem,3fr) 1fr;grid-template-columns:1fr auto minmax(37.5rem,3fr) 1fr}.nav-brand{-ms-grid-column:2;grid-column:2/3}nav{all:unset;-ms-grid-column:3;grid-column:3/4;display:flex;-webkit-box-pack:end;-ms-flex-pack:end;justify-content:flex-end;-webkit-box-align:center;-ms-flex-align:center;align-items:center}nav ul{margin-top:0;display:flex;-webkit-box-align:center;-ms-flex-align:center;align-items:center;height:auto}nav li{-webkit-box-align:center;-ms-flex-align:center;align-items:center;height:auto;margin-bottom:0;margin-left:2rem}nav a{opacity:1}}

#define MCR_FIXED_HEADERBAR_NO_CSS(in_logo, in_menu_entries...) <header id="header"><span class="nav-brand nav-heading">in_logo</span> <input class="menu-toggle" id="menu-toggle" type="checkbox"><nav class="header"><ul>in_menu_entries</ul></nav><label class="menu-nav-toggle" for="menu-toggle"><span></span></label></header>
#define MCR_FIXED_HEADERBAR(in_logo, in_menu_entries...) MCR_CUSTOM_STYLEBLOCK(MCR_FIXED_HEADERBAR_CSS) MCR_FIXED_HEADERBAR_NO_CSS(in_logo, in_menu_entries)